# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to LightSail with SSH
        run: |
            ssh -i ${{ secrets.INSTANCE_SSH_KEY }} ubuntu@${{ secrets.INSTANCE_IP }} 
            'cd the-keyboard-gallery 
            && git pull 
            && npm install 
            && pm2 restart the-keyboard-gallery'
        env:
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          INSTANCE_SSH_KEY: ${{ secrets.INSTANCE_SSH_KEY }}
          
